import { useEffect, useMemo, useState } from 'react';
import { Copy, Download, Link2, Loader2, Plus, RefreshCw, Search, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

const ROLES=['Representative','Ambassador','Patron','Life Member','Volunteer Leader','Community Connector'];
const STATUSES=['new','contacted','interested','information_shared','follow_up','engaged','joined'];

export default function PeopleConnectTab({token}:{token:string}){
 const [people,setPeople]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[showAdd,setShowAdd]=useState(false);
 const [form,setForm]=useState({personName:'',role:'Representative',profession:'',organisation:'',location:'',description:''});
 const headers={Authorization:`Bearer ${token}`};
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch(`/api/admin/connect?search=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`,{headers}),fetch('/api/admin/connect-profiles',{headers})]);setPeople(a.ok?await a.json():[]);setProfiles(b.ok?await b.json():[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[status]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/connect-profiles',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){setForm({personName:'',role:'Representative',profession:'',organisation:'',location:'',description:''});setShowAdd(false);load()}}
 async function updateStatus(id:string,s:string){await fetch(`/api/admin/connect/${id}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({engagementStatus:s})});load()}
 const qr=(code:string)=>`${window.location.origin}/connect?ref=${encodeURIComponent(code)}`;
 const filtered=useMemo(()=>people,[people]);
 return <div className="max-w-6xl mx-auto"><div className="flex flex-wrap justify-between gap-4 mb-6"><div><h2 className="text-2xl font-serif font-bold">Spandana Connect</h2><p className="text-sm text-muted-foreground mt-1">People, relationships, network members and QR introductions.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-full gap-2" onClick={load}><RefreshCw size={13}/>Refresh</Button><Button size="sm" className="rounded-full gap-2" onClick={()=>setShowAdd(!showAdd)}><Plus size={14}/>Add QR Member</Button></div></div>
 {showAdd&&<form onSubmit={saveProfile} className="border rounded-2xl bg-card p-5 mb-6 grid md:grid-cols-3 gap-4"><Field l="Name *"><Input required value={form.personName} onChange={e=>setForm({...form,personName:e.target.value})}/></Field><Field l="Role"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="w-full rounded-xl border bg-background px-3 py-2.5">{ROLES.map(x=><option key={x}>{x}</option>)}</select></Field><Field l="Profession"><Input value={form.profession} onChange={e=>setForm({...form,profession:e.target.value})}/></Field><Field l="Organisation"><Input value={form.organisation} onChange={e=>setForm({...form,organisation:e.target.value})}/></Field><Field l="Location"><Input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field l="Short description"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" className="rounded-full">Create QR Profile</Button></div></form>}
 <div className="grid lg:grid-cols-[1fr_auto] gap-3 mb-6"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Search name, WhatsApp, profession, location, interest…" className="pl-9 rounded-xl"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border bg-background px-4 py-2.5"><option value="">All statuses</option>{STATUSES.map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></div>
 <div className="grid md:grid-cols-2 gap-4 mb-10">{profiles.map(p=><div key={p.id||p._id} className="border rounded-2xl bg-card p-5"><div className="flex justify-between gap-3"><div><div className="font-semibold">{p.personName}</div><div className="text-sm text-primary">{p.role}</div></div><div className="w-20 h-20 rounded-xl border bg-white p-1"><img alt="QR code" className="w-full h-full" src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(qr(p.code))}`}/></div></div><p className="text-xs text-muted-foreground mt-3">{p.profession}{p.organisation?` · ${p.organisation}`:''}{p.location?` · ${p.location}`:''}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" className="rounded-full gap-1" onClick={()=>navigator.clipboard?.writeText(qr(p.code))}><Copy size={12}/>Copy link</Button><a href={`https://api.qrserver.com/v1/create-qr-code/?size=800x800&data=${encodeURIComponent(qr(p.code))}`} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-full border px-3 py-2 text-xs gap-1"><Download size={12}/>Open QR</a></div><div className="mt-3 text-xs text-muted-foreground">Code: {p.code}</div></div>)}</div>
 <div><div className="flex items-center gap-2 mb-3"><UserPlus size={17}/><h3 className="font-semibold">Connections</h3><span className="text-xs text-muted-foreground">{filtered.length}</span></div>{loading?<div className="py-10 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<div className="space-y-3">{filtered.map(a=><div key={a.id||a._id} className="border rounded-2xl bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{a.fullName}</div><div className="text-sm text-muted-foreground">{a.profession||'—'} · {a.location||'—'} · {a.whatsapp}</div><div className="text-xs mt-2">{(a.interest||[]).join(' · ')}</div>{a.sourcePersonName&&<div className="text-xs text-primary mt-1">Introduced by {a.sourcePersonName}</div>}</div><select value={a.engagementStatus||'new'} onChange={e=>updateStatus(a.id||a._id,e.target.value)} className="h-9 rounded-lg border bg-background px-2 text-sm">{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div></div>)}</div>}</div>
 </div>
}
function Field({l,children}:{l:string;children:any}){return <label className="block"><span className="text-xs font-medium">{l}</span><div className="mt-1">{children}</div></label>}
