import { useEffect, useState } from "react";

type Overview = { account:{recoveryEmail?:string; recoveryMobile?:string}; backupQuestionCount:number; recovery:{email:boolean;emailVerified:boolean;mobile:boolean;mobileVerified:boolean}; passwordChangedAt?:string|null };

export default function SecurityTab({showFeedback}:{showFeedback:(type:"success"|"error",msg:string)=>void}) {
  const [overview,setOverview]=useState<Overview|null>(null);
  const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirm,setConfirm]=useState("");
  const [email,setEmail]=useState(""); const [mobile,setMobile]=useState(""); const [challenge,setChallenge]=useState(""); const [otp,setOtp]=useState(""); const [contactTarget,setContactTarget]=useState<"email"|"mobile"|null>(null);
  const [questions,setQuestions]=useState([{question:"",answer:""}]); const [qPassword,setQPassword]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch('/api/v1/auth/admin/security',{credentials:'include'}); if(r.ok){const d=await r.json();setOverview(d);setEmail(d.account?.recoveryEmail||'');setMobile(d.account?.recoveryMobile||'');}}
  useEffect(()=>{load()},[]);
  async function changePassword(e:React.FormEvent){e.preventDefault();if(newPassword!==confirm){showFeedback('error','New passwords do not match');return;}setBusy(true);try{const r=await fetch('/api/v1/auth/admin/password/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword}),credentials:'include'});const d=await r.json();r.ok?showFeedback('success',d.message||'Password changed'):showFeedback('error',d.error||'Password change failed');if(r.ok){setCurrentPassword('');setNewPassword('');setConfirm('');load();}}finally{setBusy(false)}}
  async function saveContacts(){setBusy(true);try{const r=await fetch('/api/v1/auth/admin/security/recovery-details',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,mobile}),credentials:'include'});const d=await r.json();r.ok?showFeedback('success',d.message):showFeedback('error',d.error||'Update failed');if(r.ok)load();}finally{setBusy(false)}}
  async function startContact(channel:"email"|"mobile"){const target=channel==='email'?email:mobile;setContactTarget(channel);setBusy(true);try{const r=await fetch('/api/v1/auth/admin/recovery/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,identifier:target,purpose:channel==='email'?'change-email':'change-mobile'}),credentials:'include'});const d=await r.json();if(d.challenge){setChallenge(d.challenge);showFeedback('success','Verification code sent or shown by your configured development delivery.');}else showFeedback('error',d.error||'Could not start verification');}finally{setBusy(false)}}
  async function verifyContact(){setBusy(true);try{const r=await fetch('/api/v1/auth/admin/recovery/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge,otp}),credentials:'include'});const d=await r.json();r.ok?showFeedback('success',d.message||'Contact verified'):showFeedback('error',d.error||'Verification failed');if(r.ok){setChallenge('');setOtp('');setContactTarget(null);load();}}finally{setBusy(false)}}
  async function saveQuestions(){setBusy(true);try{const r=await fetch('/api/v1/auth/admin/security/backup-questions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:qPassword,questions}),credentials:'include'});const d=await r.json();r.ok?showFeedback('success',d.message):showFeedback('error',d.error||'Could not update questions');if(r.ok){setQPassword('');load();}}finally{setBusy(false)}}
  if(!overview)return <div className="p-8 text-muted-foreground">Loading account security…</div>;
  return <div className="p-6 space-y-6 max-w-4xl">
    <div><h2 className="text-2xl font-bold">Account Security</h2><p className="text-sm text-muted-foreground mt-1">Protect the Admin account with password, recovery contacts, sessions and backup recovery questions.</p></div>
    <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-bold mb-4">Password</h3><form onSubmit={changePassword} className="grid gap-3 max-w-xl"><input type="password" placeholder="Current password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3"/><input type="password" placeholder="New password (12+ characters)" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3"/><input type="password" placeholder="Confirm new password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3"/><button disabled={busy} className="rounded-xl bg-primary text-primary-foreground px-4 py-3 font-semibold">Change password</button></form></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-bold mb-1">Recovery Email & Mobile</h3><p className="text-xs text-muted-foreground mb-4">New details stay unverified until their OTP is confirmed.</p><div className="grid md:grid-cols-2 gap-3"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Recovery email" className="rounded-xl border border-input bg-background px-4 py-3"/><input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="Recovery mobile" className="rounded-xl border border-input bg-background px-4 py-3"/></div><div className="flex gap-3 mt-3"><button onClick={saveContacts} disabled={busy} className="rounded-xl border border-border px-4 py-3 font-semibold">Save contacts</button><button onClick={()=>startContact('email')} disabled={busy||!email} className="rounded-xl border border-border px-4 py-3">Verify Email</button><button onClick={()=>startContact('mobile')} disabled={busy||!mobile} className="rounded-xl border border-border px-4 py-3">Verify Mobile</button></div>{challenge&&<div className="mt-4 p-4 rounded-xl bg-muted/40 space-y-3"><div className="text-sm font-semibold">Verify {contactTarget}</div><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="6-digit code" className="rounded-xl border border-input bg-background px-4 py-3"/><button onClick={verifyContact} disabled={busy} className="rounded-xl bg-primary text-primary-foreground px-4 py-2">Confirm code</button></div>}</section>
    <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-bold mb-1">Backup Recovery Questions</h3><p className="text-xs text-muted-foreground mb-4">Optional secondary verification. Use up to 3 questions; these are never shown back to you.</p>{questions.map((q,i)=><div key={i} className="grid md:grid-cols-2 gap-3 mb-3"><input value={q.question} onChange={e=>setQuestions(xs=>xs.map((x,j)=>j===i?{...x,question:e.target.value}:x))} placeholder={`Question ${i+1}`} className="rounded-xl border border-input bg-background px-4 py-3"/><input value={q.answer} onChange={e=>setQuestions(xs=>xs.map((x,j)=>j===i?{...x,answer:e.target.value}:x))} placeholder="Answer" className="rounded-xl border border-input bg-background px-4 py-3"/></div>)}<div className="flex gap-3 mt-2"><button onClick={()=>setQuestions(xs=>xs.length<3?[...xs,{question:'',answer:''}]:xs)} disabled={questions.length>=3} className="rounded-xl border border-border px-4 py-2">+ Add question</button><input type="password" value={qPassword} onChange={e=>setQPassword(e.target.value)} placeholder="Current password" className="rounded-xl border border-input bg-background px-4 py-3 flex-1"/><button onClick={saveQuestions} disabled={busy} className="rounded-xl bg-primary text-primary-foreground px-4 py-2">Save questions</button></div><div className="text-xs text-muted-foreground mt-3">Configured questions: {overview.backupQuestionCount}</div></section>
    <section className="rounded-2xl border border-border bg-muted/30 p-5"><h3 className="font-bold">Recovery design</h3><p className="text-sm text-muted-foreground mt-1">Email/mobile OTP is the primary recovery route. Backup questions are an additional layer, not a standalone login mechanism. Password changes invalidate other Admin sessions.</p></section>
  </div>;
}
