import { useEffect, useState } from "react";
import { AlertCircle, ChevronDown, ChevronUp, Download, Loader2, RefreshCw, Trash2, UserCheck, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type VolunteerStatus = "New" | "Under Review" | "Approved" | "Rejected" | "Waitlisted" | "Withdrawn";
type VolunteerApp = {
  id:string; _id?:string; fullName:string; email:string; phone?:string; age?:string; dob?:string; address?:string; location?:string;
  occupation?:string; profession?:string; associationTypes?:string[]; qualification?:string; specialization?:string; organization?:string; role?:string; yearsExperience?:string;
  businessName?:string; industry?:string; medicalServiceYears?:string; medicalExpertise?:string[]; legalRole?:string; practiceArea?:string[]; studentCourse?:string; institution?:string; previousProfession?:string; expertise?:string;
  skills?:string|string[]; contributionTypes?:string[]; areasOfInterest?:string[]; programsOfInterest?:string[]; availability?:string[];
  associations?:string; connectionSource?:string; referralName?:string; referralPhone?:string; referralCity?:string; sourceDetail?:string; sourceType?:string; sourceId?:string; connectorName?:string; connectorType?:string; helpRequested?:string[]; helpMessage?:string; futureRoles?:string[];
  emergencyContactName?:string; emergencyContactPhone?:string; motivation?:string; message?:string; declaration?:boolean; childrenDeclaration?:boolean; status?:VolunteerStatus; submittedAt:string;
};
const STATUSES:VolunteerStatus[]=["New","Under Review","Approved","Rejected","Waitlisted","Withdrawn"];

export default function VolunteerAppsTab({token}:{token:string}){
  const [apps,setApps]=useState<VolunteerApp[]>([]); const [loading,setLoading]=useState(true); const [expanded,setExpanded]=useState<string|null>(null); const [deleting,setDeleting]=useState<string|null>(null); const [statusUpdating,setStatusUpdating]=useState<string|null>(null); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState<"All"|VolunteerStatus>("All"); const [error,setError]=useState("");
  const load=()=>{setLoading(true);fetch("/api/admin/volunteers?page=1&limit=1000",{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>{setApps(Array.isArray(d)?d:[]);setLoading(false)}).catch(()=>{setError("Could not load applications.");setLoading(false)})};
  useEffect(()=>{load()},[]);
  async function updateStatus(id:string,status:VolunteerStatus){setStatusUpdating(id);setError("");try{const r=await fetch(`/api/admin/volunteers/${id}/status`,{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({status})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Status update failed");setApps(a=>a.map(x=>x.id===id?{...x,status}:x))}catch(e){setError(e instanceof Error?e.message:"Status update failed")}finally{setStatusUpdating(null)}}
  async function del(id:string){if(!confirm("Remove this application from the server?"))return;setDeleting(id);setError("");try{const r=await fetch(`/api/admin/volunteers/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error("Delete failed");load()}catch(e){setError(e instanceof Error?e.message:"Delete failed")}finally{setDeleting(null)}}
  function csv(){if(!apps.length)return;const headers=["Submitted At","Status","Name","Email","WhatsApp/Mobile","Location","Profession","Specialization","Qualification","Organization","Role","Experience","Medical Service Years","Medical Expertise","Legal Role","Practice Area","Associations","Connection Source","QR/Source ID","Connected Through","Referrer Name","Referrer Mobile","Referrer City","Source Detail","Skills","Interests","Help Requested","Future Relationship Interest","Message"];const cell=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;const rows=apps.map(a=>[a.submittedAt,a.status??"New",a.fullName,a.email,a.phone,a.location||a.address,a.profession||a.occupation,a.specialization,a.qualification,a.organization,a.role,a.yearsExperience,a.medicalServiceYears,(a.medicalExpertise||[]).join("; "),a.legalRole,(a.practiceArea||[]).join("; "),a.associations,a.sourceType||a.connectionSource,a.sourceId,a.connectorName,a.referralName,a.referralPhone,a.referralCity,a.sourceDetail,(Array.isArray(a.skills)?a.skills:[]).join("; "),(a.areasOfInterest||[]).join("; "),(a.helpRequested||[]).join("; "),(a.futureRoles||[]).join("; "),a.message||a.motivation]);const blob=new Blob([[headers,...rows].map(r=>r.map(cell).join(",")).join("\n")],{type:"text/csv"});const u=URL.createObjectURL(blob);const el=document.createElement("a");el.href=u;el.download="spandana-join-us-applications.csv";el.click();URL.revokeObjectURL(u)}
  const q=search.trim().toLowerCase();const filtered=apps.filter(a=>(statusFilter==="All"||(a.status??"New")===statusFilter)&&(!q||[a.fullName,a.email,a.phone,a.location,a.address,a.profession,a.occupation,a.organization,a.role,a.businessName,a.industry,a.qualification,a.specialization,(a.associationTypes||[]).join(" "),(a.contributionTypes||[]).join(" ")].some(v=>String(v||"").toLowerCase().includes(q))));
  const Field=({label,value}:{label:string,value:any})=>value?<div><p className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">{label}</p><p className="text-sm mt-0.5 break-words">{Array.isArray(value)?value.join(", "):value}</p></div>:null;
  return <div className="max-w-5xl mx-auto">
    {error&&<div className="mb-5 rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive flex gap-2"><AlertCircle size={15}/>{error}</div>}
    <div className="flex flex-wrap items-start justify-between gap-4 mb-6"><div><h2 className="text-2xl font-serif font-bold">Join Us Connections</h2><p className="text-sm text-muted-foreground mt-1">Review people by profession, expertise, networks, source and interests — not as job applications.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-full gap-2" onClick={load}><RefreshCw size={14}/>Refresh</Button><Button variant="outline" size="sm" className="rounded-full gap-2" onClick={csv} disabled={!apps.length}><Download size={14}/>Export CSV</Button></div></div>
    <div className="grid md:grid-cols-[1fr_auto] gap-3 mb-5"><Input className="rounded-xl" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, WhatsApp, profession, location, expertise, organization…"/><div className="flex flex-wrap gap-2">{(["All",...STATUSES] as const).map(s=><Button key={s} size="sm" className="rounded-full" variant={statusFilter===s?"default":"outline"} onClick={()=>setStatusFilter(s)}>{s}</Button>)}</div></div>
    {loading?<div className="py-16 flex justify-center gap-2 text-muted-foreground"><Loader2 className="animate-spin" size={18}/>Loading…</div>:!filtered.length?<div className="py-16 text-center text-muted-foreground"><UserPlus className="mx-auto mb-3 opacity-30"/><p className="font-medium">{search?"No matches found":"No applications yet"}</p></div>:<div className="space-y-3">{filtered.map(a=><div key={a.id} className="rounded-2xl border border-border bg-card overflow-hidden">
      <button type="button" className="w-full px-5 py-4 flex items-center justify-between gap-4 text-left hover:bg-muted/30" onClick={()=>setExpanded(expanded===a.id?null:a.id)}><div className="flex items-center gap-3 min-w-0"><div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0"><UserCheck size={16}/></div><div className="min-w-0"><p className="font-semibold truncate">{a.fullName}</p><p className="text-xs text-muted-foreground truncate">{a.profession||a.occupation||"—"}{a.location?` · ${a.location}`:""}</p></div></div><div className="flex items-center gap-3 shrink-0"><span className="rounded-full border border-border px-2.5 py-1 text-[11px]">{a.status??"New"}</span><span className="hidden md:block text-xs text-muted-foreground">{new Date(a.submittedAt).toLocaleDateString("en-IN")}</span>{expanded===a.id?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</div></button>
      {expanded===a.id&&<div className="border-t border-border p-5 bg-muted/10"><div className="flex flex-wrap justify-between gap-4 mb-5"><div><p className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground mb-1">Application status</p><select value={a.status??"New"} onChange={e=>updateStatus(a.id,e.target.value as VolunteerStatus)} disabled={statusUpdating===a.id} className="h-9 rounded-lg border border-border bg-background px-3 text-sm">{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>{statusUpdating===a.id&&<Loader2 className="animate-spin" size={16}/>}</div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-5 gap-y-4"><Field label="Email" value={a.email}/><Field label="WhatsApp / Mobile" value={a.phone}/><Field label="Location" value={a.location||a.address}/><Field label="Date of birth / Age" value={a.dob?`${a.dob}${a.age?` · ${a.age}`:""}`:a.age}/><Field label="Associations / Networks" value={a.associations||a.associationTypes}/><Field label="Profession" value={a.profession||a.occupation}/><Field label="Qualification" value={a.qualification}/><Field label="Specialization" value={a.specialization}/><Field label="Organization" value={a.organization}/><Field label="Role" value={a.role}/><Field label="Experience" value={a.yearsExperience}/><Field label="Medical Service Years" value={a.medicalServiceYears}/><Field label="Medical Expertise" value={a.medicalExpertise}/><Field label="Legal Role" value={a.legalRole}/><Field label="Practice Area" value={a.practiceArea}/><Field label="Business" value={a.businessName}/><Field label="Industry" value={a.industry}/><Field label="Student Course" value={a.studentCourse}/><Field label="Institution" value={a.institution}/><Field label="Previous Profession" value={a.previousProfession}/><Field label="Expertise" value={a.expertise}/><Field label="Contributions" value={a.contributionTypes||a.areasOfInterest}/><Field label="Programs" value={a.programsOfInterest}/><Field label="Availability" value={a.availability}/><Field label="Connection Source" value={a.sourceType||a.connectionSource}/><Field label="QR / Source ID" value={a.sourceId}/><Field label="Connected Through" value={a.connectorName}/><Field label="Connector Type" value={a.connectorType}/><Field label="Referrer Name" value={a.referralName}/><Field label="Referrer Mobile" value={a.referralPhone}/><Field label="Referrer City" value={a.referralCity}/><Field label="Source Detail" value={a.sourceDetail}/><Field label="Help Requested" value={a.helpRequested}/><Field label="Future Relationship Interest" value={a.futureRoles}/></div>
        {(a.message||a.motivation||a.helpMessage)&&<div className="mt-5"><p className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">Message</p><p className="text-sm leading-relaxed mt-1">{a.message||a.motivation||a.helpMessage}</p></div>}
        {(a.emergencyContactName||a.emergencyContactPhone)&&<div className="mt-5 grid sm:grid-cols-2 gap-4"><Field label="Parent / Guardian" value={a.emergencyContactName}/><Field label="Guardian phone" value={a.emergencyContactPhone}/></div>}
        <p className="text-xs text-muted-foreground mt-5">Declaration: {a.declaration?"Accepted":"—"} · Children safeguarding: {a.childrenDeclaration?"Accepted":"—"} · Submitted: {new Date(a.submittedAt).toLocaleString("en-IN")}</p>
        <div className="flex justify-end mt-5"><Button variant="destructive" size="sm" className="rounded-full gap-2" onClick={()=>del(a.id)} disabled={deleting===a.id}>{deleting===a.id?<Loader2 size={13} className="animate-spin"/>:<Trash2 size={13}/>}Delete</Button></div>
      </div>}
    </div>)}</div>}
  </div>;
}
