import { Router } from 'express';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { validate } from '../../middleware/validate.js';
import { requireAdmin, requireTeam } from '../../middleware/auth.js';
import { z } from 'zod';
import { rateLimit } from 'express-rate-limit';
import * as ctrl from '../../controllers/authController.js';
const LoginSchema=z.object({password:z.string().min(1)}); const TeamSchema=z.object({username:z.string().min(1),password:z.string().min(1)});
const authLimiter=rateLimit({windowMs:15*60*1000,max:10,standardHeaders:true,legacyHeaders:false,message:{error:'Too many authentication attempts. Please try again later.'}});
const resetLimiter=rateLimit({windowMs:15*60*1000,max:8,standardHeaders:true,legacyHeaders:false,message:{error:'Too many recovery attempts. Please try again later.'}});
const router=Router();
router.post('/auth/admin/login',authLimiter,validate(LoginSchema),asyncHandler(ctrl.adminLogin));
router.get('/auth/admin/session',requireAdmin,asyncHandler(ctrl.adminSession));
router.post('/auth/admin/password/change',authLimiter,requireAdmin,asyncHandler(ctrl.changeAdminPassword));
router.post('/auth/admin/recovery/start',resetLimiter,asyncHandler(ctrl.recoveryStart));
router.post('/auth/admin/recovery/verify-otp',resetLimiter,asyncHandler(ctrl.recoveryVerifyOtp));
router.post('/auth/admin/recovery/verify-answers',resetLimiter,asyncHandler(ctrl.recoveryVerifyAnswers));
router.post('/auth/admin/recovery/reset',resetLimiter,asyncHandler(ctrl.recoveryReset));
router.get('/auth/admin/security',requireAdmin,asyncHandler(ctrl.securityOverview));
router.put('/auth/admin/security/recovery-details',authLimiter,requireAdmin,asyncHandler(ctrl.updateRecoveryDetails));
router.put('/auth/admin/security/backup-questions',authLimiter,requireAdmin,asyncHandler(ctrl.updateBackupQuestions));
router.get('/auth/team/session',requireTeam,asyncHandler(ctrl.teamSession));
router.post('/auth/team/login',authLimiter,validate(TeamSchema),asyncHandler(ctrl.teamLogin));
router.post('/auth/logout',asyncHandler(ctrl.logout));
export default router;
