import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Heart, Gift } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { supportService } from "@/services/supportService";
import type { DonationOpportunity } from "@/services/donationTypes";

export default function ImpactCalculator(){
 const [cfg,setCfg]=useState<any>({}); const [rows,setRows]=useState<DonationOpportunity[]>([]); const [selected,setSelected]=useState(0); const [geo,setGeo]=useState<'india'|'intl'>('india'); const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([fetch('/api/settings').then(r=>r.ok?r.json():{}),supportService.catalog()]).then(([s,c])=>{setCfg(s?.impactSection||{});setRows(c?.opportunities||[])}).finally(()=>setLoading(false));fetch('https://ipapi.co/json/').then(r=>r.json()).then(d=>{if(d?.country_code&&d.country_code!=='IN')setGeo('intl')}).catch(()=>{})},[]);
 const items=useMemo(()=>rows.filter(r=>r.active&&r.published&&(r.geography==='both'||r.geography===(geo==='india'?'india':'international'))),[rows,geo]); const idx=Math.min(selected,Math.max(items.length-1,0)); const item=items[idx];
 return <section id="impact" className="py-16 md:py-24"><div className="max-w-5xl mx-auto px-4 sm:px-6"><div className="flex items-center justify-between gap-3 mb-5"><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/8 text-primary text-xs font-bold uppercase tracking-widest">Your Impact</div></div><h2 className="text-3xl md:text-5xl font-serif font-medium">{cfg.heading||'See what your donation'} <span className="italic text-muted-foreground">{cfg.headingItalic||'actually does.'}</span></h2><p className="text-muted-foreground mt-3">{cfg.subtitle||'Every contribution should have a clear purpose. Pick an opportunity below.'}</p>{loading?<div className="py-10 text-center text-sm text-muted-foreground">Loading current opportunities…</div>:!item?<div className="py-10 text-sm text-muted-foreground">No current impact opportunities.</div>:<><div className="flex flex-wrap gap-2 mt-7 mb-6">{items.map((r,i)=><button key={r.id} onClick={()=>setSelected(i)} className={`px-4 py-2 rounded-full border text-sm font-semibold ${i===idx?'bg-primary text-primary-foreground border-primary':''}`}>{r.icon||'❤️'} {r.title}</button>)}</div><motion.div key={item.id} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="border rounded-3xl p-5 md:p-8 bg-card flex flex-col md:flex-row gap-6 items-center"><div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center"><Gift className="text-primary" size={38}/></div><div className="flex-1 text-center md:text-left"><p className="text-xs uppercase tracking-widest text-muted-foreground">{item.type==='unit'?'Unit-based giving':'Direct support'}</p><h3 className="text-2xl font-serif mt-1">{item.title}</h3><p className="text-muted-foreground mt-2">{item.impactText||item.description}</p></div><Button asChild size="lg" className="rounded-full gap-2"><Link href={`/donate?supportId=${encodeURIComponent(item.id)}`}>Donate <ArrowRight size={17}/></Link></Button></motion.div></>}</div></section>
}
