import { useEffect, useState } from 'react';
import { ArchiveRestore, Loader2, Trash2, RefreshCw, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SectionCard } from '@/pages/admin/tabs/shared';
import { api } from '@/services/api.js';

type TrashItem = { id:string; entityType:string; entityLabel?:string; originalId:string; snapshot?:Record<string,unknown>; deletedAt?:string; deletedBy?:string };

export default function RecycleBinTab({ showFeedback }:{showFeedback?:(type:'success'|'error',msg:string)=>void}) {
  const [items,setItems]=useState<TrashItem[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const load=async()=>{setLoading(true);try{setItems(await api.get('/admin/recycle-bin',true));}catch(e){showFeedback?.('error',e instanceof Error?e.message:'Could not load Recycle Bin.');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const restore=async(id:string)=>{setBusy(id);try{await api.post(`/admin/recycle-bin/${id}/restore`,{},true);showFeedback?.('success','Item restored.');await load();}catch(e){showFeedback?.('error',e instanceof Error?e.message:'Could not restore item.');}finally{setBusy('')}};
  const permanentDelete=async(id:string)=>{if(!confirm('Permanently delete this item? This cannot be undone.'))return;setBusy(id);try{await api.delete(`/admin/recycle-bin/${id}`,true);showFeedback?.('success','Item permanently deleted.');await load();}catch(e){showFeedback?.('error',e instanceof Error?e.message:'Could not permanently delete item.');}finally{setBusy('')}};
  const empty=async()=>{if(!items.length)return;if(!confirm('Empty the Recycle Bin? All deleted items will be permanently removed.'))return;setBusy('all');try{await api.delete('/admin/recycle-bin',true);showFeedback?.('success','Recycle Bin emptied.');await load();}catch(e){showFeedback?.('error',e instanceof Error?e.message:'Could not empty Recycle Bin.');}finally{setBusy('')}};
  return <div className="space-y-5">
    <SectionCard title="Recycle Bin" defaultOpen>
      <div className="flex items-center justify-between gap-3 mb-4"><div><p className="text-sm font-medium">Deleted items are kept here instead of being lost.</p><p className="text-xs text-muted-foreground mt-1">Restore an item to return it to its original Admin module. Permanent deletion is irreversible.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-full gap-2" onClick={()=>void load()} disabled={loading}><RefreshCw size={13}/>Refresh</Button><Button variant="outline" size="sm" className="rounded-full gap-2 text-destructive" onClick={()=>void empty()} disabled={!items.length||busy==='all'}><Trash2 size={13}/>Empty Bin</Button></div></div>
      {loading?<div className="py-16 flex justify-center"><Loader2 className="animate-spin text-primary"/></div>:items.length?<div className="grid gap-3">{items.map(item=><div key={item.id} className="rounded-2xl border border-border/70 bg-background p-4 flex flex-col sm:flex-row sm:items-center gap-4"><div className="w-10 h-10 rounded-xl bg-muted flex items-center justify-center shrink-0"><Trash2 size={17} className="text-muted-foreground"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><p className="font-semibold text-sm truncate">{item.entityLabel||item.entityType}</p><span className="text-[10px] uppercase tracking-wider rounded-full bg-muted px-2 py-1 text-muted-foreground">{item.entityType}</span></div><p className="text-xs text-muted-foreground mt-1">Deleted {item.deletedAt?new Date(item.deletedAt).toLocaleString():'—'} · Original ID {item.originalId}</p></div><div className="flex gap-2 shrink-0"><Button size="sm" className="rounded-full gap-1.5" onClick={()=>void restore(item.id)} disabled={busy===item.id}><ArchiveRestore size={13}/>{busy===item.id?'Restoring…':'Restore'}</Button><Button size="sm" variant="outline" className="rounded-full gap-1.5 text-destructive" onClick={()=>void permanentDelete(item.id)} disabled={busy===item.id}><Trash2 size={13}/>Delete forever</Button></div></div>)}</div>:<div className="py-14 text-center rounded-2xl border border-dashed border-border/70"><ArchiveRestore size={28} className="mx-auto text-muted-foreground mb-2"/><p className="font-medium text-sm">Recycle Bin is empty</p><p className="text-xs text-muted-foreground mt-1">Deleted Admin records will appear here.</p></div>}
      <div className="mt-4 flex gap-2 rounded-xl bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900/40 p-3"><AlertTriangle size={15} className="text-amber-600 shrink-0 mt-0.5"/><p className="text-[11px] text-amber-800 dark:text-amber-300">The Recycle Bin protects records removed through Admin delete actions. Permanent deletion is the only irreversible action.</p></div>
    </SectionCard>
  </div>;
}
