
const $=id=>document.getElementById(id); async function api(u,o={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(u,{...o,signal:controller.signal,headers:{'content-type':'application/json',...(o.headers||{})}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text||r.statusText||'Invalid server response'}}if(!r.ok){const err=new Error(d.error || ('Request failed ('+r.status+')'));err.status=r.status;err.details=d;throw err}return d}catch(e){if(e?.name==='AbortError') throw new Error('SER request timed out. Please make sure the Recovery Console service is running on port 5051.');throw e}finally{clearTimeout(timer)}}
async function sendCode(){try{const d=await api('./api/auth/start',{method:'POST',body:JSON.stringify({email:$('email').value})});window.challenge=d.challenge||'';$('loginMsg').textContent=d.message;$('otpBox').classList.remove('hidden')}catch(e){$('loginMsg').textContent=e.message}}
async function selfTest(){await action('./api/self-test')}
async function verifyCode(){try{await api('./api/auth/verify',{method:'POST',body:JSON.stringify({email:$('email').value,otp:$('otp').value,challenge:window.challenge||''})});$('login').classList.add('hidden');$('console').classList.remove('hidden');load()}catch(e){$('loginMsg').textContent=e.message}}
async function load(){try{const d=await api('./api/status');const safe=v=>String(v??'None').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const backups=d.backups||[];const good=backups.filter(x=>String(x.status).toLowerCase()==='good').length;const candidates=backups.length-good;$('status').innerHTML='<div class="card"><b class="'+(d.health.ok?'ok':'warn')+'">'+(d.health.ok?'🟢 Application responding':'🔴 Application unavailable')+'</b><br>Last verified good: <b>'+safe(d.latestGood)+'</b><br>Backup count: '+d.backupCount+'</div>';$('pointsSummary').textContent=good+' GOOD · '+candidates+' candidate · '+backups.length+' total';$('points').innerHTML=backups.map(x=>'<div class="card"><b>'+safe(x.id)+'</b><br>Status: '+safe(x.status)+' · '+safe(x.reason)+'<br>Created: '+safe(x.createdAt)+'<br><button class="primary" onclick="restore(&quot;'+encodeURIComponent(x.id)+'&quot;)">Restore this point</button></div>').join('')||'No recovery points yet.'}catch(e){if(e.message.includes('verification')){location.reload();}else $('status').textContent=e.message}}
async function action(url,body){$('log').textContent='Working…';try{const d=await api(url,{method:'POST',body:JSON.stringify(body||{})});const prefix=d.verified===false?'⚠️ BACKUP CREATED — CANDIDATE (NOT VERIFIED GOOD)\n\n':d.verified===true?'✅ BACKUP CREATED — VERIFIED GOOD\n\n':'';$('log').textContent=prefix+JSON.stringify(d,null,2);setTimeout(load,1000);return d}catch(e){$('log').textContent='ERROR'+(e.status?' ('+e.status+')':'')+': '+e.message+'\n\n'+(e.details?JSON.stringify(e.details,null,2):'');return null}}
async function recover(){if(!confirm('Recover the LAST VERIFIED GOOD system? The current state will be preserved first when possible.'))return;await action('./api/recover')}
async function restore(id){id=decodeURIComponent(id);if(!confirm('Restore '+id+'? The current state will be preserved first when possible.'))return;await action('./api/restore',{id})}
async function backup(){await action('./api/backup')};async function restart(){if(!confirm('Restart the application?'))return;await action('./api/restart')};async function health(){await action('./api/health')};async function logout(){await api('./api/logout',{method:'POST'});location.reload()}
async function showConfig(){try{const d=await api('./api/config-status');let html=d.otpReady?'🟢 <b>Email OTP: CONFIGURED</b>':'🟠 <b>Email OTP: CHECK CONFIGURATION</b>';html+='<br>SMTP credentials: <b>'+ (d.emailDeliveryConfigured?'CONFIGURED':'MISSING') +'</b>';html+='<br>Sender: '+(d.sender||'Not configured');html+='<br>Recovery email: '+(d.recoveryEmail||'Not configured');if(d.smtpError)html+='<br><span class="warn">'+d.smtpError+'</span>';if(d.duplicateEnvKeys?.length)html+='<br><span class="warn">Duplicate .env keys: '+d.duplicateEnvKeys.join(', ')+'</span>';$('config').innerHTML=html}catch(e){$('config').textContent='Unable to read recovery configuration: '+e.message}}
async function init(){try{await showConfig();const d=await api('./api/session');if(d.authenticated){$('login').classList.add('hidden');$('console').classList.remove('hidden');await load()}}catch(e){console.error('[SER] initialization failed:',e);const el=$('config');if(el)el.innerHTML='<b class="warn">⚠️ Recovery Console initialization failed.</b><br><span class="muted">The Recovery Console server is responding, but the browser could not complete page initialization.</span><br><small>'+String(e?.message||e).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))+'</small>'}}window.addEventListener('error',e=>{console.error('[SER] browser error:',e.error||e.message);const el=$('config');if(el&&el.textContent.includes('Loading recovery status'))el.innerHTML='<b class="warn">⚠️ Recovery Console page script error.</b><br><span class="muted">The server is available. Please report this message to the system administrator.</span>'});window.addEventListener('unhandledrejection',e=>console.error('[SER] unhandled rejection:',e.reason));window.addEventListener('DOMContentLoaded',()=>init());
