import { useEffect, useState } from 'react';
import { useParams, Link } from 'wouter';
import { Button } from '@/components/ui/button';
import type { FundraisingCampaign } from '@/services/supportTypes';

const publicNames: Record<string,string> = { needs:'What the campaign needs', volunteers:'Ways to volunteer', skills:'Skills we need', sponsorship:'Sponsorship opportunities', inkind:'Goods and services needed', beneficiaries:'Who this helps & expected impact', team:'Campaign contacts', location:'Location & logistics', documents:'Documents', partners:'Partners & supporters', updates:'Campaign updates' };
const hidden=['enabled','public','items'];
function cleanLabel(k:string){return k.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
function show(v:any){if(v===undefined||v===null||v==='')return false;if(typeof v==='boolean')return v;if(Array.isArray(v))return v.length>0;return true}
export default function CampaignDetail(){const {id}=useParams<{id:string}>();const [c,setC]=useState<FundraisingCampaign|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{fetch('/api/v1/support/catalog').then(r=>r.json()).then(d=>setC((d.campaigns||[]).find((x:FundraisingCampaign)=>x.id===id)||null)).finally(()=>setLoading(false))},[id]);
 if(loading)return <main className="max-w-5xl mx-auto px-4 py-16">Loading campaign…</main>; if(!c)return <main className="max-w-5xl mx-auto px-4 py-16"><h1 className="text-2xl font-semibold">Campaign not found</h1><Link href="/donate"><Button className="mt-4 rounded-full">Support other causes</Button></Link></main>;
 const d:any=c.campaignDetails||{}; return <main className="max-w-5xl mx-auto px-4 py-10 space-y-8"><div className="flex justify-between gap-3"><Link href="/donate" className="text-sm underline">← Support</Link><button className="text-sm underline" onClick={()=>navigator.clipboard?.writeText(window.location.href)}>Copy link</button></div>{c.image&&<img src={c.image} alt="" className="w-full max-h-[420px] object-cover rounded-3xl"/>}<header><h1 className="text-4xl font-serif font-bold">{c.title}</h1><p className="mt-3 text-lg text-muted-foreground">{d.basic?.shortDescription||c.description}</p>{d.basic?.story&&<p className="mt-4 whitespace-pre-line">{d.basic.story}</p>}<div className="mt-6 flex flex-wrap gap-3"><Link href={`/donate?campaignId=${encodeURIComponent(c.id)}`}><Button className="rounded-full px-6">Support Now</Button></Link>{c.startDate&&<span className="rounded-full border px-4 py-2 text-sm">Starts {new Date(c.startDate).toLocaleDateString()}</span>}{c.endDate&&<span className="rounded-full border px-4 py-2 text-sm">Ends {new Date(c.endDate).toLocaleDateString()}</span>}</div></header>{d.goal?.enabled!==false&&(c.targetAmount||c.targetQuantity)&&<section className="rounded-3xl border p-6"><h2 className="text-xl font-semibold">Our goal</h2>{c.targetAmount&&d.goal?.showAmountRaised!==false&&<p className="mt-2 text-2xl font-semibold">Target: {c.currency==='USD'?'$':'₹'}{Number(c.targetAmount).toLocaleString()}</p>}{c.targetQuantity&&d.goal?.showTargetQuantity!==false&&<p className="text-sm text-muted-foreground mt-1">Target quantity: {c.targetQuantity}</p>}</section>}{Object.entries(publicNames).map(([key,title])=>{const sec=d[key];if(!sec||sec.enabled===false||sec.public===false)return null;const items=Array.isArray(sec.items)?sec.items:[];return <section key={key} className="rounded-3xl border p-6"><h2 className="text-xl font-semibold">{title}</h2>{items.length?items.map((it:any,i:number)=><div key={i} className="mt-4 rounded-2xl bg-muted/30 p-4"><h3 className="font-semibold">{it.title||it.name||it.role||it.skill||`Item ${i+1}`}</h3><div className="mt-2 grid md:grid-cols-2 gap-x-6 gap-y-2 text-sm">{Object.entries(it).filter(([k,v])=>!hidden.includes(k)&&show(v)).map(([k,v])=><div key={k}><span className="text-muted-foreground">{cleanLabel(k)}: </span>{typeof v==='boolean'?(v?'Yes':'No'):Array.isArray(v)?v.join(', '):String(v)}</div>)}</div></div>):<p className="mt-2 text-sm text-muted-foreground">{sec.description||''}</p>}</section>})}<div className="flex justify-center pb-10"><Link href={`/donate?campaignId=${encodeURIComponent(c.id)}`}><Button className="rounded-full px-8">Support This Campaign</Button></Link></div></main>}
