import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Brain, CheckCircle2, HeartHandshake, Shield, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

interface Highlight { label?: string; value?: string; visible?: boolean; order?: number; }
interface PillarConfig {
  enabled?: boolean; heroVisible?: boolean; heroBadgeVisible?: boolean; heroTitleVisible?: boolean; heroDescriptionVisible?: boolean; heroImageVisible?: boolean;
  highlightsVisible?: boolean; introVisible?: boolean; whyVisible?: boolean; focusVisible?: boolean; programsVisible?: boolean; programHeadingVisible?: boolean; programSubtextVisible?: boolean;
  ctaVisible?: boolean; ctaHeadingVisible?: boolean; ctaDescriptionVisible?: boolean; ctaButton1Visible?: boolean; ctaButton2Visible?: boolean; backLinkVisible?: boolean;
  badge?: string; title?: string; titleItalic?: string; heroDescription?: string; heroImage?: string; introHeading?: string; intro?: string; whyHeading?: string; whyBody?: string;
  focusHeading?: string; focusBody?: string; programSectionHeading?: string; programSectionSubtext?: string; programCardCta?: string; backToProgramsLabel?: string; backToProgramsHref?: string;
  ctaHeading?: string; ctaDescription?: string; ctaButton1?: string; ctaButton1Href?: string; ctaButton2?: string; ctaButton2Href?: string; highlights?: Highlight[];
}
interface Settings { saharaPage?: { pillars?: { physical?: PillarConfig; mental?: PillarConfig } } }
interface Program { id?: string; _id?: string; title: string; description?: string; pillar: string; image?: string; imageAlt?: string; published?: boolean; status?: string; order?: number; }

const defaults: Record<"physical"|"mental",PillarConfig> = {
 physical:{enabled:true,heroVisible:true,heroBadgeVisible:true,heroTitleVisible:true,heroDescriptionVisible:true,heroImageVisible:true,highlightsVisible:true,introVisible:true,whyVisible:true,focusVisible:true,programsVisible:true,programHeadingVisible:true,programSubtextVisible:true,ctaVisible:true,ctaHeadingVisible:true,ctaDescriptionVisible:true,ctaButton1Visible:true,ctaButton2Visible:true,backLinkVisible:true,badge:"Physical Care",title:"Physical",titleItalic:"Care",heroDescription:"Building healthier, stronger and more capable communities through health, education, recreation, skills, environmental responsibility and resilience.",introHeading:"What Physical Care means",intro:"Physical Care addresses the practical foundations of wellbeing. It brings together programs that help people stay healthy, learn, build useful skills, participate in community life and become more resilient.",whyHeading:"Why this matters",whyBody:"Good health and opportunity are closely connected. When people can access information, preventative care, education, skills and supportive community networks, they are better positioned to make confident choices and build stable futures.",focusHeading:"Our approach",focusBody:"Spandana works through awareness, knowledge and advice — creating pathways rather than dependency and connecting people with appropriate programs, professionals, institutions and opportunities.",programSectionHeading:"Our Physical Care Programs",programSectionSubtext:"Explore all current Physical Care programs. Program cards and detailed content are managed centrally under Core Programs.",programCardCta:"Read More",backToProgramsLabel:"Back to Programs",backToProgramsHref:"/sahara#core-pillars",ctaHeading:"Help strengthen Physical Care",ctaDescription:"Volunteer, partner, provide expertise or support a program that helps communities become healthier and more capable.",ctaButton1:"Get Involved",ctaButton1Href:"/get-involved",ctaButton2:"Back to Core Pillars",ctaButton2Href:"/sahara#core-pillars",highlights:[{label:"Care area",value:"Health, learning, skills & resilience",visible:true,order:1},{label:"Programs",value:"Live from Core Programs",visible:true,order:2},{label:"Approach",value:"Awareness · Knowledge · Advice",visible:true,order:3}]},
 mental:{enabled:true,heroVisible:true,heroBadgeVisible:true,heroTitleVisible:true,heroDescriptionVisible:true,heroImageVisible:true,highlightsVisible:true,introVisible:true,whyVisible:true,focusVisible:true,programsVisible:true,programHeadingVisible:true,programSubtextVisible:true,ctaVisible:true,ctaHeadingVisible:true,ctaDescriptionVisible:true,ctaButton1Visible:true,ctaButton2Visible:true,backLinkVisible:true,badge:"Mental Care",title:"Mental",titleItalic:"Care",heroDescription:"Creating spaces where people can talk, connect, grow, navigate life challenges and find appropriate support without shame.",introHeading:"What Mental Care means",intro:"Mental Care focuses on emotional wellbeing, healthy relationships, personal growth, resilience and practical support. It recognises that people often need a safe conversation and trusted guidance before they are ready for formal services.",whyHeading:"Why this matters",whyBody:"Mental wellbeing affects families, education, work, relationships and community participation. Accessible awareness and supportive conversations can help people recognise challenges earlier and connect to appropriate care.",focusHeading:"Our approach",focusBody:"Spandana creates safe, respectful pathways for awareness, knowledge and advice while recognising when professional, emergency or specialist support is needed.",programSectionHeading:"Our Mental Care Programs",programSectionSubtext:"Explore all current Mental Care programs. Program cards and detailed content are managed centrally under Core Programs.",programCardCta:"Read More",backToProgramsLabel:"Back to Programs",backToProgramsHref:"/sahara#core-pillars",ctaHeading:"Help strengthen Mental Care",ctaDescription:"Help create safe spaces, awareness and pathways to support for people and families facing life's challenges.",ctaButton1:"Get Involved",ctaButton1Href:"/get-involved",ctaButton2:"Back to Core Pillars",ctaButton2Href:"/sahara#core-pillars",highlights:[{label:"Care area",value:"Connection, growth & wellbeing",visible:true,order:1},{label:"Programs",value:"Live from Core Programs",visible:true,order:2},{label:"Approach",value:"Awareness · Knowledge · Advice",visible:true,order:3}]}
};

export default function PillarPage(){
 const [location]=useLocation(); const kind: "physical"|"mental"=location.includes("/mental-care")||location.includes("/mental-health")?"mental":"physical";
 const [config,setConfig]=useState<PillarConfig>(defaults[kind]); const [programs,setPrograms]=useState<Program[]>([]);
 useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then((d:Settings)=>setConfig({...defaults[kind],...(d.saharaPage?.pillars?.[kind]??{})})).catch(()=>{});fetch("/api/programs").then(r=>r.json()).then(d=>setPrograms(Array.isArray(d)?d:[])).catch(()=>{})},[kind]);
 const list=useMemo(()=>programs.filter(p=>p.pillar===kind&&p.published!==false&&p.status==="active").sort((a,b)=>(a.order??0)-(b.order??0)),[programs,kind]);
 const isMental=kind==="mental"; const Icon=isMental?Brain:Shield; const accent="text-primary"; const soft="bg-primary/10";
 const parentHref="/sahara#core-pillars";
 if(config.enabled===false)return <><Nav/><main className="min-h-[70vh] pt-32 flex items-center justify-center text-muted-foreground">This care pillar is currently unavailable.</main><Footer/></>;
 return <><Nav/><main className="pt-16">
 {config.heroVisible!==false&&<section className="relative overflow-hidden bg-primary px-6 md:px-12 py-16 md:py-24"><div className="absolute inset-0 pointer-events-none opacity-[0.07]" style={{backgroundImage:"radial-gradient(circle, #fff 1px, transparent 1px)",backgroundSize:"32px 32px"}}/><div className="relative z-10 max-w-6xl mx-auto">{config.backLinkVisible!==false&&<Link href={parentHref} className="inline-flex items-center gap-2 text-white/80 hover:text-white text-sm font-semibold mb-8"><ArrowLeft size={15}/>{config.backToProgramsLabel}</Link>}<div className={`grid ${config.heroImage&&config.heroImageVisible!==false?"md:grid-cols-[1.05fr_.95fr]":"md:grid-cols-[1fr_auto]"} gap-10 items-center`}><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.65}}>{config.heroBadgeVisible!==false&&<div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/15 border border-white/25 text-white text-xs font-bold uppercase tracking-widest mb-5"><Sparkles size={12}/>{config.badge}</div>}{config.heroTitleVisible!==false&&<h1 className="text-4xl md:text-6xl font-serif font-medium text-white leading-tight">{config.title} <span className="italic text-white/75">{config.titleItalic}</span></h1>}{config.heroDescriptionVisible!==false&&<div className="text-white/70 text-base md:text-lg leading-relaxed mt-5 max-w-2xl" dangerouslySetInnerHTML={{__html:config.heroDescription??""}}/>}</motion.div>{config.heroImage&&config.heroImageVisible!==false?<img src={config.heroImage} alt={config.title} className="w-full aspect-[4/3] object-cover rounded-3xl border border-white/15 shadow-2xl"/>:<div className="hidden md:flex justify-center"><div className={`w-40 h-40 rounded-[2rem] ${soft} flex items-center justify-center`}><Icon size={72} className={accent}/></div></div>}</div></div></section>}

 {(config.introVisible!==false||config.whyVisible!==false||config.focusVisible!==false)&&<section className="py-16 md:py-20 px-6 md:px-12 bg-background"><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-10">{config.introVisible!==false&&<div className="rounded-3xl border border-border bg-card p-7 md:p-9"><div className={`w-12 h-12 rounded-2xl ${soft} flex items-center justify-center mb-5`}><HeartHandshake size={23} className={accent}/></div><p className={`text-xs font-bold uppercase tracking-widest ${accent} mb-2`}>{config.introHeading}</p><div className="text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{__html:config.intro??""}}/></div>}{config.whyVisible!==false&&<div className="rounded-3xl border border-border bg-card p-7 md:p-9"><div className={`w-12 h-12 rounded-2xl ${soft} flex items-center justify-center mb-5`}><CheckCircle2 size={23} className={accent}/></div><p className={`text-xs font-bold uppercase tracking-widest ${accent} mb-2`}>{config.whyHeading}</p><div className="text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{__html:config.whyBody??""}}/></div>}</div>{config.focusVisible!==false&&<div className="max-w-5xl mx-auto mt-10 rounded-3xl border border-border bg-card p-7 md:p-9"><div className="flex items-center gap-3 mb-3"><div className={`w-10 h-10 rounded-xl ${soft} flex items-center justify-center`}><Icon size={19} className={accent}/></div><h2 className="text-xl md:text-2xl font-serif font-semibold">{config.focusHeading}</h2></div><div className="text-muted-foreground leading-relaxed max-w-4xl" dangerouslySetInnerHTML={{__html:config.focusBody??""}}/></div>}</section>}
 {config.programsVisible!==false&&<section className="py-16 md:py-24 px-6 md:px-12 bg-foreground/[0.02] border-y border-border"><div className="max-w-6xl mx-auto"><div className="text-center max-w-3xl mx-auto mb-12">{config.programHeadingVisible!==false&&<><p className={`text-[10px] uppercase tracking-widest font-bold ${accent} mb-3`}>{config.badge}</p><h2 className="text-2xl md:text-4xl font-serif font-medium">{config.programSectionHeading}</h2></>}{config.programSubtextVisible!==false&&<div className="text-muted-foreground mt-3" dangerouslySetInnerHTML={{__html:config.programSectionSubtext??""}}/>}</div>{list.length===0?<div className="max-w-xl mx-auto text-center py-12 rounded-2xl border border-dashed border-border text-sm text-muted-foreground">No active programs are currently published in this care area.</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{list.map((p,i)=>{const id=p.id??p._id;return <motion.article key={id??p.title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.04}} className="bg-card border border-border rounded-2xl overflow-hidden hover:border-primary/30 hover:shadow-lg transition-all"><div className="h-44 overflow-hidden"><img src={p.image|| (isMental?"/images/mental.png":"/images/physical.png")} alt={p.imageAlt||p.title} className="w-full h-full object-cover"/></div><div className="p-6 flex flex-col h-full"><h3 className="font-serif font-semibold text-lg leading-snug">{p.title}</h3>{p.description&&<p className="text-sm text-muted-foreground leading-relaxed mt-3">{p.description}</p>}{id&&<Link href={`/programs/${id}`} className={`inline-flex items-center gap-2 mt-5 text-xs font-bold ${accent}`}>{config.programCardCta}<ArrowRight size={13}/></Link>}</div></motion.article>})}</div>}<div className="sahara-pillar-bottom-nav max-w-6xl mx-auto mt-10 pt-8 border-t border-border"><Link href={parentHref} className="sahara-pillar-nav-button sahara-pillar-nav-back"><ArrowLeft size={17}/><span>{config.backToProgramsLabel || "Back to Programs"}</span></Link><Link href={isMental?"/programs/physical-care":"/programs/mental-care"} className="sahara-pillar-nav-button sahara-pillar-nav-next"><span className="sahara-pillar-nav-destination-row"><span className="sahara-pillar-nav-destination">{isMental?"Physical Care":"Mental Care"}</span><ArrowRight size={17}/></span></Link></div></div></section>}
 {config.ctaVisible!==false&&<section className="py-20 px-6 md:px-12 bg-primary text-center"><div className="max-w-2xl mx-auto">{config.ctaHeadingVisible!==false&&<h2 className="text-2xl md:text-4xl font-serif font-medium text-white">{config.ctaHeading}</h2>}{config.ctaDescriptionVisible!==false&&<div className="text-white/70 mt-4 mb-8" dangerouslySetInnerHTML={{__html:config.ctaDescription??""}}/>}<div className="flex flex-wrap justify-center gap-4">{config.ctaButton1Visible!==false&&<Link href={config.ctaButton1Href??"/get-involved"} className="inline-flex items-center gap-2 bg-white text-primary font-bold px-7 py-3 rounded-full text-sm">{config.ctaButton1}<ArrowRight size={15}/></Link>}{config.ctaButton2Visible!==false&&<Link href={parentHref} className="inline-flex items-center gap-2 border-2 border-white/40 text-white font-bold px-7 py-3 rounded-full text-sm hover:border-white"><ArrowLeft size={15}/>{config.ctaButton2}</Link>}</div></div></section>}
 </main><Footer/></>;
}
