import { useEffect, useMemo, useState, type ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useForm, type UseFormReturn } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { CheckCircle2, ChevronDown, ChevronRight, HeartHandshake, Loader2, MapPin, ShieldCheck, User, Search, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Form, FormControl, FormField, FormItem, FormLabel } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

type PathwayField = { key:string; label:string; type:"text"|"number"|"select"|"multi"; placeholder?:string; options?:string[]; visible?:boolean };
type VolunteerConfig = {
  banner:any; form:any; labels:any; placeholders:any;
  mainProfessionOptions:string[]; additionalProfessionOptions:string[];
  professionOptions:string[]; specializations:Record<string,string[]>;
  skillsOptions:string[]; interestOptions:string[]; contributionOptions:string[];
  connectionOptions:string[]; helpOptions:string[]; futureRoles:any[];
  professionalPathways:Record<string,{fields:PathwayField[]}>; side:any; dobMessages:any;
};
const DEFAULT:VolunteerConfig={
 banner:{image:"/images/volunteer-hero-people-back.png",desktopImage:"/images/volunteer-header-desktop.png",mobileImage:"/images/volunteer-header-mobile.jpg",eyebrow:"Spandana People & Participation",heading:"Let’s Connect. Let’s Make a Difference.",subheading:"Everyone has something valuable to share.",supportingText:"Be part of a caring community working for healthier people, stronger families and a more hopeful society.",buttonLabel:"Let’s Know About You",tagline:"Together We Grow. Together We Care.",benefits:[{title:"Serve",text:"Make a real difference in people’s lives"},{title:"Share",text:"Use your skills for a meaningful cause"},{title:"Support",text:"Be part of a compassionate community"},{title:"Empower",text:"Help build stronger, healthier communities"}]},
 form:{pageTitle:"Let’s get to know each other",introHeading:"Let’s Know About You",introDescription:"A simple introduction is all we need. You can tell us more as your connection grows.",sectionProfessional:"Your Professional World",sectionProfessionalDescription:"Choose your main profession and any other professional backgrounds that describe you.",sectionSkills:"What You Bring",sectionSkillsDescription:"Select the skills and interests that feel right for you.",sectionContribution:"How would you like to connect?",sectionContributionDescription:"There are many ways to be part of the Spandana network.",sectionReference:"Your introduction",sectionReferenceDescription:"If someone introduced you to Spandana, tell us who.",sectionHelp:"Would you like help from Spandana?",sectionHelpDescription:"Optional — you can tell us if there is something you would like to discuss.",submitLabel:"Connect with Spandana",submittingLabel:"Connecting…",consentLabel:"Stay connected with Spandana",consentText:"I agree that Spandana may use these details to contact me about this connection.",otherLabel:"Other",otherPlaceholder:"Please specify",selectPlaceholder:"Search or choose",doneLabel:"Done",qrCapturedText:"Your Spandana Connect QR source has been captured automatically.",guardianNameLabel:"Parent / guardian name",guardianPhoneLabel:"Parent / guardian mobile",successEyebrow:"Connection received",successHeading:"Thank you for connecting with Spandana.",successText:"We are glad to be connected. We look forward to getting to know you.",successExploreLabel:"Explore our work",errors:{generic:"Something went wrong. Please try again."},validationSummary:"Please complete the required information above."},
 labels:{name:"Full name",profession:"Main profession",additionalProfessions:"Additional professions / backgrounds",specialization:"Specialisation",phone:"WhatsApp / mobile",email:"Email",location:"City / location",dob:"Date of birth",organization:"Current organisation / workplace",role:"Current role",qualification:"Qualification",yearsExperience:"Years of experience",skills:"Skills & expertise",interests:"Areas of interest",contribution:"How would you like to connect / contribute?",connectionSource:"How did you connect with Spandana?",referralName:"Reference name",referralPhone:"Reference WhatsApp / mobile",referralCity:"Reference city",helpRequested:"How can Spandana help?",helpMessage:"A little more detail"},
 placeholders:{name:"Your name",profession:"Search profession",additionalProfessions:"Search and select",specialization:"Search and select",phone:"9876543210",email:"you@example.com",location:"Search city / location",organization:"Organisation / workplace",role:"Search current role",qualification:"Search qualification",yearsExperience:"Years",helpMessage:"Optional short note"},
 mainProfessionOptions:["Doctor / Medical Practitioner","Dentist","Nurse / Nursing Professional","Physiotherapist / Rehabilitation","Pharmacist","Mental Health Professional / Counsellor","Psychologist","Teacher / School Educator","Professor / Lecturer / Academic","Researcher / Scientist","Student","Lawyer / Advocate","IAS / Civil Services","IPS / Police Services","Government / Public Service","Defence / Armed Forces","Entrepreneur / Business Owner","Corporate Executive / Management","Finance / Accounting","HR","Marketing / Sales","Banking / Insurance","Business Consultant","Engineer","IT / Software / Technology","Architect","Data / AI / Analytics","Technical Specialist","Social Worker","NGO / Development Professional","Community Leader","Church / Faith Leader","Media / Journalist","Communications / PR","Writer / Author","Artist / Designer / Creative","Photographer / Videographer","Skilled Worker / Technician","Artisan / Craftsperson","Agriculture / Farming","Homemaker","Retired Professional","Seeking Employment / Career Transition","Other"],
 additionalProfessionOptions:[], professionOptions:[], specializations:{}, skillsOptions:["Leadership","Public Speaking","Training","Teaching","Healthcare","Counselling","Business Development","Technology","Finance","Administration","Event Support","Community Development","Research","Communication","Design / Creative","Networking","Other"], interestOptions:["Physical Care","Mental Care","Education","Children","Youth","Healthcare","Community Development","Skills & Training","Community Initiatives","Other"], contributionOptions:["Volunteer","Share Professional Expertise","Mentor","Advisor / Consultant","Training / Teaching","Introduce People / Network","Support a Community Initiative","Partnership","Sponsorship / Patronage","Event Support","Other"], connectionOptions:["Someone introduced me","Other"],helpOptions:["Information / Guidance","Counselling / Someone to Talk To","Health-related guidance","Education / Learning","Skills / Training","Community support","Other"],futureRoles:[],professionalPathways:{},side:{personHeading:"People matter",personText:"Spandana grows through genuine relationships, experience and shared purpose.",privacyHeading:"Your information",privacyText:"We use your details to understand this connection and communicate appropriately.",locationHeading:"Your community",locationText:"Your location helps us understand where relationships are growing.",closingHeading:"Together we grow",closingText:"Every connection can become an opportunity to care."},dobMessages:{birthday:"Happy Birthday! We are glad to connect with you.",age:"Welcome to the {age} Club — your experience and energy matter."}
};
function mergeConfig(raw:any):VolunteerConfig{const r=raw||{};const form={...DEFAULT.form,...(r.form||{})};const labels={...DEFAULT.labels,...(r.labels||{})};const placeholders={...DEFAULT.placeholders,...(r.placeholders||{})};const main=r.mainProfessionOptions?.length?r.mainProfessionOptions:(r.professionOptions?.length?r.professionOptions:DEFAULT.mainProfessionOptions);return {...DEFAULT,...r,form,labels,placeholders,mainProfessionOptions:main,additionalProfessionOptions:r.additionalProfessionOptions?.length?r.additionalProfessionOptions:main,professionOptions:main,skillsOptions:r.skillsOptions?.length?r.skillsOptions:DEFAULT.skillsOptions,interestOptions:r.interestOptions?.length?r.interestOptions:DEFAULT.interestOptions,contributionOptions:r.contributionOptions?.length?r.contributionOptions:DEFAULT.contributionOptions,connectionOptions:r.connectionOptions?.length?r.connectionOptions:DEFAULT.connectionOptions,helpOptions:r.helpOptions?.length?r.helpOptions:DEFAULT.helpOptions,professionalPathways:r.professionalPathways||{},specializations:r.specializations||{},side:{...DEFAULT.side,...(r.side||{})},banner:{...DEFAULT.banner,...(r.banner||{}),buttonLabel:r.banner?.buttonLabel === "Start Your Connection" ? "Let’s Know About You" : (r.banner?.buttonLabel || DEFAULT.banner.buttonLabel),desktopImage:r.banner?.desktopImage||DEFAULT.banner.desktopImage,mobileImage:r.banner?.mobileImage||DEFAULT.banner.mobileImage}};}
function calculateAge(dob?:string){if(!dob)return null;const b=new Date(`${dob}T00:00:00`);if(Number.isNaN(b.getTime()))return null;const now=new Date();let age=now.getFullYear()-b.getFullYear();if(now<new Date(now.getFullYear(),b.getMonth(),b.getDate()))age--;if(age<0||age>120)return null;return{age,birthday:now.getMonth()===b.getMonth()&&now.getDate()===b.getDate()};}
const schema=z.object({fullName:z.string().trim().min(2),mainProfession:z.string().trim().min(2),mainProfessionOther:z.string().optional(),additionalProfessions:z.array(z.string()).optional(),additionalProfessionsOther:z.array(z.string()).optional(),phone:z.string().trim().min(7),email:z.string().trim().email(),location:z.string().trim().min(2),dob:z.string().optional(),specialization:z.array(z.string()).optional(),specializationOther:z.array(z.string()).optional(),qualification:z.string().optional(),qualificationOther:z.string().optional(),organization:z.string().optional(),role:z.string().optional(),yearsExperience:z.string().optional(),skills:z.array(z.string()).optional(),skillsOther:z.array(z.string()).optional(),interests:z.array(z.string()).optional(),interestsOther:z.array(z.string()).optional(),contributionTypes:z.array(z.string()).optional(),contributionOther:z.array(z.string()).optional(),connectionSource:z.string().optional(),referralName:z.string().optional(),referralPhone:z.string().optional(),referralCity:z.string().optional(),connectionOther:z.string().optional(),helpRequested:z.array(z.string()).optional(),helpRequestedOther:z.array(z.string()).optional(),helpMessage:z.string().optional(),professionalProfiles:z.record(z.any()).optional(),sourceType:z.string().optional(),sourceId:z.string().optional(),connectorName:z.string().optional(),connectorType:z.string().optional(),emergencyContactName:z.string().optional(),emergencyContactPhone:z.string().optional(),consent:z.boolean().refine(Boolean)}).passthrough().superRefine((d,c)=>{const a=calculateAge(d.dob)?.age;if(a!=null&&a<18){if(!d.emergencyContactName)c.addIssue({code:"custom",path:["emergencyContactName"],message:"Required"});if(!d.emergencyContactPhone)c.addIssue({code:"custom",path:["emergencyContactPhone"],message:"Required"});}});
type FormData=z.infer<typeof schema>;
function SearchMulti({label,options,value,onChange,otherValues,onOtherChange,placeholder,otherLabel,doneLabel}:{label:string;options:string[];value:string[];onChange:(v:string[])=>void;otherValues:string[];onOtherChange:(v:string[])=>void;placeholder:string;otherLabel:string;doneLabel:string}){const[open,setOpen]=useState(false);const[q,setQ]=useState("");const filtered=options.filter(x=>x.toLowerCase().includes(q.toLowerCase()));const toggle=(x:string)=>onChange(value.includes(x)?value.filter(v=>v!==x):[...value,x]);return <div className="relative"><p className="text-sm font-medium mb-2">{label}</p><button type="button" onClick={()=>setOpen(v=>!v)} className="min-h-12 w-full rounded-2xl border bg-background px-4 py-3 text-left flex items-center justify-between gap-3"><span className="text-sm truncate">{[...value,...otherValues].join(", ")||placeholder}</span><ChevronDown size={17}/></button>{open&&<div className="absolute z-40 mt-2 w-full rounded-2xl border bg-card shadow-2xl p-3"><div className="flex items-center gap-2 rounded-xl border px-3 mb-2"><Search size={15}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder} className="h-10 w-full bg-transparent outline-none text-sm"/></div><div className="max-h-64 overflow-auto">{filtered.map(o=><label key={o} className="flex items-center gap-3 px-2 py-2 rounded-xl hover:bg-muted cursor-pointer"><Checkbox checked={value.includes(o)} onCheckedChange={()=>toggle(o)}/><span className="text-sm">{o}</span></label>)}<label className="flex items-center gap-3 px-2 py-2 rounded-xl hover:bg-muted cursor-pointer"><Checkbox checked={value.includes(otherLabel)} onCheckedChange={()=>toggle(otherLabel)}/><span className="text-sm font-medium">{otherLabel}</span></label></div>{value.includes(otherLabel)&&<div className="mt-2 space-y-2">{otherValues.map((v,i)=><Input key={i} value={v} onChange={e=>{const a=[...otherValues];a[i]=e.target.value;onOtherChange(a)}} placeholder="Please specify"/>)}<Button type="button" variant="outline" size="sm" onClick={()=>onOtherChange([...otherValues,""])}><Plus size={14} className="mr-1"/>Add another</Button></div>}<Button type="button" className="w-full mt-3 rounded-xl" onClick={()=>setOpen(false)}>{doneLabel}</Button></div>}</div>}
function SearchSingle({label,options,value,onChange,placeholder,otherLabel,onOther}:{label:string;options:string[];value:string;onChange:(v:string)=>void;placeholder:string;otherLabel:string;onOther:(v:string)=>void}){const[open,setOpen]=useState(false);const[q,setQ]=useState("");const filtered=options.filter(x=>x.toLowerCase().includes(q.toLowerCase()));const other=value===otherLabel;return <div className="relative"><p className="text-sm font-medium mb-2">{label}</p><button type="button" onClick={()=>setOpen(v=>!v)} className="h-12 w-full rounded-2xl border bg-background px-4 text-left flex items-center justify-between"><span className="truncate">{value||placeholder}</span><ChevronDown size={17}/></button>{open&&<div className="absolute z-40 mt-2 w-full rounded-2xl border bg-card shadow-2xl p-3"><div className="flex items-center gap-2 rounded-xl border px-3"><Search size={15}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder} className="h-10 w-full bg-transparent outline-none text-sm"/></div><div className="max-h-64 overflow-auto mt-2">{filtered.map(o=><button type="button" key={o} onClick={()=>{onChange(o);setOpen(false)}} className="w-full text-left px-3 py-2 rounded-xl hover:bg-muted text-sm">{o}</button>)}</div></div>}{other&&<Input className="mt-2" value={q||""} onChange={e=>onOther(e.target.value)} placeholder="Please specify"/>}</div>}
function Section({title,description,children,icon:Icon=HeartHandshake}:{title:string;description?:string;children:ReactNode;icon?:any}){return <motion.section initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.45}} className="scroll-mt-24"><div className="mb-5 flex items-start gap-3"><div className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-[#0750b5] ring-1 ring-blue-100"><Icon size={19}/></div><div><h2 className="text-[1.45rem] md:text-[1.65rem] font-semibold tracking-tight text-[#102a56]">{title.replace(/^\s*\d+[.)-]\s*/, "")}</h2>{description&&<p className="mt-1 text-sm leading-6 text-slate-600">{description}</p>}</div></div>{children}</motion.section>}
function Field({form,name,label,children}:{form:UseFormReturn<any>;name:any;label:string;children:(field:any)=>ReactNode}){return <FormField control={form.control} name={name} render={({field})=><FormItem><FormLabel className="text-[13px] font-semibold text-[#173b70]">{label}</FormLabel><FormControl>{children(field)}</FormControl></FormItem>}/>}

export default function VolunteerPage(){
 const[cfg,setCfg]=useState<VolunteerConfig>(DEFAULT);const[loading,setLoading]=useState(true);const[submitted,setSubmitted]=useState(false);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");const[existing,setExisting]=useState<any>(null);const[qrSource,setQrSource]=useState<any>({id:""});
 const f=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{fullName:"",mainProfession:"",mainProfessionOther:"",additionalProfessions:[],additionalProfessionsOther:[],phone:"",email:"",location:"",dob:"",specialization:[],specializationOther:[],qualification:"",qualificationOther:"",organization:"",role:"",yearsExperience:"",skills:[],skillsOther:[],interests:[],interestsOther:[],contributionTypes:[],contributionOther:[],connectionSource:"",referralName:"",referralPhone:"",referralCity:"",connectionOther:"",helpRequested:[],helpRequestedOther:[],helpMessage:"",professionalProfiles:{},consent:false}});
 const main=f.watch("mainProfession")||"";const additional=f.watch("additionalProfessions")||[];const dob=f.watch("dob");const source=f.watch("connectionSource")||"";const age=useMemo(()=>calculateAge(dob),[dob]);
 const allProfessions=[...new Set([...cfg.mainProfessionOptions,...cfg.additionalProfessionOptions])];const selectedProfessions=[main,...additional.filter(x=>x!==cfg.form.otherLabel)];const pathwayKeys=selectedProfessions.filter(Boolean);
 const qr=p=>{const id=p.get("qr")||p.get("connect")||p.get("sourceId")||"";if(id)setQrSource({id,name:p.get("referrerName")||p.get("connector")||undefined,type:p.get("sourceType")||undefined});};
 useEffect(()=>{let live=true;fetch("/api/v1/settings",{credentials:"same-origin"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(live)setCfg(mergeConfig(d?.volunteerPage));}).catch(()=>{if(live)setCfg(DEFAULT)}).finally(()=>{if(live)setLoading(false)});qr(new URLSearchParams(window.location.search));return()=>{live=false}},[]);
 const phone=f.watch("phone");const email=f.watch("email");
 useEffect(()=>{if(phone&&email&&phone.replace(/\D/g,"").length>=7&&email.includes("@")){const t=setTimeout(()=>fetch("/api/v1/volunteers/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,email})}).then(r=>r.ok?r.json():null).then(d=>{if(d?.exists)setExisting(d)}).catch(()=>{}),650);return()=>clearTimeout(t)}},[phone,email]);
 const onSubmit=async(data:FormData)=>{setSubmitting(true);setError("");const custom={additionalProfessionsOther:data.additionalProfessionsOther||[],specializationOther:data.specializationOther||[],skillsOther:data.skillsOther||[],interestsOther:data.interestsOther||[],contributionOther:data.contributionOther||[],helpRequestedOther:data.helpRequestedOther||[],connectionOther:data.connectionOther||[]};const payload={...data,profession:data.mainProfession,occupation:data.mainProfession,address:data.location,age:age?.age,additionalProfessions:data.additionalProfessions,sourceType:qrSource.type||undefined,sourceId:qrSource.id||undefined,connectorName:qrSource.name||undefined,connectorType:qrSource.type||undefined,...custom};try{const r=await fetch("/api/v1/volunteers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||cfg.form.errors.generic);setSubmitted(true)}catch(e:any){setError(e.message||cfg.form.errors.generic)}finally{setSubmitting(false)}};
 if(submitted)return <div data-page="volunteer" className="min-h-screen bg-[#f7f9fc] flex flex-col"><Nav/><main className="flex-1 flex items-center justify-center px-5 py-16"><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="max-w-xl text-center rounded-[2rem] border border-blue-100 bg-white p-10 shadow-[0_24px_70px_rgba(10,45,100,.12)]"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={38}/></div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-[#0750b5]">{cfg.form.successEyebrow}</p><h1 className="mt-3 text-3xl font-semibold text-[#102a56]">{cfg.form.successHeading}</h1><p className="mt-4 text-slate-600">{cfg.form.successText}</p><Button className="mt-7 rounded-full bg-[#0750b5] px-6" onClick={()=>window.location.href="/"}>{cfg.form.successExploreLabel}</Button></motion.div></main><Footer/></div>;
 return <div className="min-h-screen bg-[#fbfaf7] text-[#102a56]"><Nav/><div aria-hidden="true" className="h-[28px] md:h-[28px]" />{loading?<div className="min-h-[70vh] flex items-center justify-center"><div className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-white shadow-sm"><Loader2 className="animate-spin text-[#0750b5]"/></div><p className="mt-3 text-sm text-slate-500">Loading your connection experience…</p></div></div>:<>
 <section aria-label="Spandana volunteer invitation" className="w-full overflow-hidden bg-white">
  <div className="relative w-full">
   <picture className="block w-full">
    {cfg.banner.mobileImage&&<source media="(max-width: 767px)" srcSet={cfg.banner.mobileImage} />}
    <img src={cfg.banner.desktopImage||cfg.banner.image||"/images/volunteer-header-desktop.png"} alt="People making change together with Spandana" className="block h-auto w-full" loading="eager" decoding="async" fetchPriority="high" />
   </picture>
   <a href="#join-form" aria-label={cfg.banner.buttonLabel||"Let’s Know About You"} onClick={(e)=>{e.preventDefault();const target=document.getElementById("join-form");if(target){window.scrollTo({top:Math.max(0,target.getBoundingClientRect().top+window.scrollY-16),behavior:"smooth"});}}} className="absolute left-[7%] bottom-[14%] hidden h-[10%] min-h-11 w-[58%] items-center justify-center gap-2 rounded-full bg-[#0750b5] px-4 text-center text-[clamp(.7rem,1.15vw,1.35rem)] font-semibold text-white shadow-[0_10px_28px_rgba(7,80,181,.24)] transition hover:bg-[#06479f] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/90 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0750b5] md:left-[7.1%] md:right-auto md:bottom-[23%] md:inline-flex md:h-[8%] md:w-[19%] md:min-h-0">{cfg.banner.buttonLabel||"Let’s Know About You"}<ChevronRight className="h-[1.15em] w-[1.15em] shrink-0"/></a>
  </div>
 </section>
 <main className="mx-auto max-w-[1380px] px-4 py-8 sm:px-6 md:py-10 lg:px-8"><div className="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_300px] xl:gap-8">
  <Form {...f}><form onSubmit={f.handleSubmit(onSubmit)} className="rounded-[1.6rem] border border-blue-100 bg-white p-5 shadow-[0_18px_55px_rgba(14,52,105,.08)] sm:p-7 lg:p-8">
   <div id="join-form" className="mb-7 border-b border-slate-100 pb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0a67bd]">Spandana People & Participation</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-[#102a56]">{cfg.form.introHeading}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{cfg.form.introDescription}</p></div>
   <div className="space-y-9 md:space-y-10">
    <Section title="Personal Details" description="Tell us a little about yourself. These details help us begin the connection." icon={User}><div className="grid gap-5 md:grid-cols-2"><Field form={f} name="fullName" label={cfg.labels.name}>{field=><Input {...field} className="h-11 rounded-xl border-slate-200" placeholder={cfg.placeholders.name}/>}</Field><Field form={f} name="phone" label={cfg.labels.phone}>{field=><Input {...field} className="h-11 rounded-xl border-slate-200" inputMode="tel" placeholder={cfg.placeholders.phone}/>}</Field><Field form={f} name="email" label={cfg.labels.email}>{field=><Input {...field} className="h-11 rounded-xl border-slate-200" type="email" placeholder={cfg.placeholders.email}/>}</Field><Field form={f} name="location" label={cfg.labels.location}>{field=><Input {...field} className="h-11 rounded-xl border-slate-200" placeholder={cfg.placeholders.location}/>}</Field></div>{existing&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-5 rounded-xl border border-blue-100 bg-blue-50/70 p-4"><p className="font-semibold text-[#173b70]">We found an existing Spandana connection.</p><p className="mt-1 text-sm text-slate-600">Your details can be enriched rather than creating another connection.</p></motion.div>}</Section>
    <Section title={cfg.form.sectionProfessional} description={cfg.form.sectionProfessionalDescription} icon={HeartHandshake}><div className="space-y-5"><SearchSingle label={cfg.labels.profession} options={cfg.mainProfessionOptions} value={main} onChange={v=>f.setValue("mainProfession",v,{shouldValidate:true})} placeholder={cfg.placeholders.profession} otherLabel={cfg.form.otherLabel} onOther={v=>f.setValue("mainProfessionOther",v)}/><SearchMulti label={cfg.labels.additionalProfessions} options={allProfessions.filter(x=>x!==main)} value={additional} onChange={v=>f.setValue("additionalProfessions",v)} otherValues={f.watch("additionalProfessionsOther")||[]} onOtherChange={v=>f.setValue("additionalProfessionsOther",v)} placeholder={cfg.placeholders.additionalProfessions} otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/>{pathwayKeys.map(p=>{const fields=cfg.professionalPathways?.[p]?.fields||[];const specs=cfg.specializations?.[p]||[];return <motion.div key={p} initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} className="rounded-2xl border border-blue-100 bg-[#f8fbff] p-4 md:p-5"><h3 className="text-base font-semibold text-[#173b70]">{p}</h3>{specs.length>0&&<div className="mt-4"><SearchMulti label={cfg.labels.specialization} options={specs} value={f.watch("specialization")||[]} onChange={v=>f.setValue("specialization",v)} otherValues={f.watch("specializationOther")||[]} onOtherChange={v=>f.setValue("specializationOther",v)} placeholder={cfg.placeholders.specialization} otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/></div>}<div className="mt-4 grid gap-5 md:grid-cols-2">{fields.map(field=>field.key!=="specialization"&&<Field key={field.key} form={f} name={field.key as any} label={field.label}>{ff=>field.type==="select"?<select {...ff} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">{cfg.form.selectPlaceholder}</option>{(field.options||[]).map(o=><option key={o}>{o}</option>)}</select>:field.type==="multi"?<SearchMulti label="" options={field.options||[]} value={ff.value||[]} onChange={ff.onChange} otherValues={[]} onOtherChange={()=>{}} placeholder={field.placeholder||cfg.form.selectPlaceholder} otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/>:<Input {...ff} className="h-11 rounded-xl border-slate-200" type={field.type==="number"?"number":"text"} placeholder={field.placeholder}/>}</Field>)}</div></motion.div>})}</div></Section>
    <Section title={cfg.form.sectionSkills} description={cfg.form.sectionSkillsDescription} icon={Sparkles}><div className="grid gap-5 md:grid-cols-2"><SearchMulti label={cfg.labels.skills} options={cfg.skillsOptions} value={f.watch("skills")||[]} onChange={v=>f.setValue("skills",v)} otherValues={f.watch("skillsOther")||[]} onOtherChange={v=>f.setValue("skillsOther",v)} placeholder="Search skills" otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/><SearchMulti label={cfg.labels.interests} options={cfg.interestOptions} value={f.watch("interests")||[]} onChange={v=>f.setValue("interests",v)} otherValues={f.watch("interestsOther")||[]} onOtherChange={v=>f.setValue("interestsOther",v)} placeholder="Search interests" otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/></div></Section>
    <Section title={cfg.form.sectionContribution} description={cfg.form.sectionContributionDescription} icon={HeartHandshake}><SearchMulti label={cfg.labels.contribution} options={cfg.contributionOptions} value={f.watch("contributionTypes")||[]} onChange={v=>f.setValue("contributionTypes",v)} otherValues={f.watch("contributionOther")||[]} onOtherChange={v=>f.setValue("contributionOther",v)} placeholder="Search ways to connect" otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/></Section>
    <Section title={cfg.form.sectionReference} description={cfg.form.sectionReferenceDescription} icon={MapPin}>{qrSource.id?<div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#0750b5]"><Sparkles size={16} className="mr-2 inline"/>{cfg.form.qrCapturedText}</div>:<><SearchSingle label={cfg.labels.connectionSource} options={cfg.connectionOptions} value={source} onChange={v=>f.setValue("connectionSource",v)} placeholder={cfg.form.selectPlaceholder} otherLabel={cfg.form.otherLabel} onOther={v=>f.setValue("connectionOther",v)}/>{source==="Someone introduced me"&&<div className="mt-5 grid gap-5 md:grid-cols-2"><Field form={f} name="referralName" label={cfg.labels.referralName}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200" placeholder="Reference name"/>}</Field><Field form={f} name="referralPhone" label={cfg.labels.referralPhone}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200" inputMode="tel" placeholder={cfg.placeholders.phone}/>}</Field></div>}{source==="Other"&&<Field form={f} name="connectionOther" label={cfg.form.otherLabel}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200" placeholder={cfg.form.otherPlaceholder}/>}</Field>}</>}</Section>
    <Section title={cfg.form.sectionHelp} description={cfg.form.sectionHelpDescription} icon={ShieldCheck}><SearchMulti label={cfg.labels.helpRequested} options={cfg.helpOptions} value={f.watch("helpRequested")||[]} onChange={v=>f.setValue("helpRequested",v)} otherValues={f.watch("helpRequestedOther")||[]} onOtherChange={v=>f.setValue("helpRequestedOther",v)} placeholder="Search help options" otherLabel={cfg.form.otherLabel} doneLabel={cfg.form.doneLabel}/>{(f.watch("helpRequested")||[]).length>0&&<div className="mt-5"><Field form={f} name="helpMessage" label={cfg.labels.helpMessage}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200" placeholder={cfg.placeholders.helpMessage}/>}</Field></div>}</Section>
   </div>
   <section className="mt-10 rounded-2xl border border-blue-100 bg-[#f7fbff] p-5 sm:p-6"><div className="flex items-start gap-3"><Checkbox checked={f.watch("consent")} onCheckedChange={v=>f.setValue("consent",Boolean(v),{shouldValidate:true})}/><div><p className="text-sm font-semibold text-[#173b70]">{cfg.form.consentLabel}</p><p className="mt-1 text-xs leading-5 text-slate-600">{cfg.form.consentText}</p></div></div>{age&&age.age<18&&<div className="mt-5 grid gap-5 md:grid-cols-2"><Field form={f} name="emergencyContactName" label={cfg.form.guardianNameLabel}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200"/>}</Field><Field form={f} name="emergencyContactPhone" label={cfg.form.guardianPhoneLabel}>{ff=><Input {...ff} className="h-11 rounded-xl border-slate-200" inputMode="tel"/>}</Field></div>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end"><Button type="submit" disabled={submitting} size="lg" className="h-11 rounded-full bg-[#0750b5] px-6 text-sm font-semibold shadow-[0_8px_20px_rgba(7,80,181,.18)] hover:bg-[#06479f]">{submitting?<><Loader2 className="mr-2 animate-spin"/>{cfg.form.submittingLabel}</>:<>{cfg.form.submitLabel}<ChevronRight className="ml-1"/></>}</Button></div>{f.formState.isSubmitted&&Object.keys(f.formState.errors).length>0&&<p className="mt-3 text-right text-sm text-red-600">{cfg.form.validationSummary}</p>}</section>
  </form></Form>
  <aside className="hidden lg:block space-y-4 lg:sticky lg:top-24"><div className="rounded-[1.35rem] border border-blue-100 bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><User size={19}/></div><h3 className="mt-3 text-lg font-semibold text-[#173b70]">{cfg.side.personHeading}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{cfg.side.personText}</p></div><div className="rounded-[1.35rem] border border-blue-100 bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-[#0750b5]"><ShieldCheck size={19}/></div><h3 className="mt-3 text-lg font-semibold text-[#173b70]">{cfg.side.privacyHeading}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{cfg.side.privacyText}</p></div><div className="rounded-[1.35rem] border border-blue-100 bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-sky-600"><MapPin size={19}/></div><h3 className="mt-3 text-lg font-semibold text-[#173b70]">{cfg.side.locationHeading}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{cfg.side.locationText}</p></div><div className="rounded-[1.35rem] bg-[#0750b5] p-5 text-white shadow-[0_18px_40px_rgba(7,80,181,.22)]"><HeartHandshake/><h3 className="mt-3 text-lg font-semibold">{cfg.side.closingHeading}</h3><p className="mt-2 text-sm leading-6 text-white/80">{cfg.side.closingText}</p></div></aside>
 </div></main></> }<Footer/></div>}
