import mongoose from 'mongoose';
import crypto from 'node:crypto';
import path from 'node:path';
import { isDbConnected } from '../config/db.js';
import { jsonModel } from './base.js';
import { env } from '../config/env.js';
const jm=jsonModel(path.join(env.DATA_DIR,'team-sessions.json'));
const schema=new mongoose.Schema({tokenHash:{type:String,unique:true,required:true},memberId:String,username:String,createdAt:Date,lastActivityAt:Date,expiresAt:Date,revokedAt:{type:Date,default:null},ip:String,userAgent:String});
const Mongo=mongoose.models.TeamSession||mongoose.model('TeamSession',schema);
const hash=t=>crypto.createHash('sha256').update(t).digest('hex'); const raw=()=>crypto.randomBytes(32).toString('base64url'); const TTL=8*60*60*1000;
export const TeamSession={async create({memberId,username,ip='',userAgent=''}){const r=raw(),d={tokenHash:hash(r),memberId,username,createdAt:new Date(),lastActivityAt:new Date(),expiresAt:new Date(Date.now()+TTL),ip,userAgent}; if(isDbConnected()) await Mongo.create(d); else jm.create({...d,id:crypto.randomUUID(),createdAt:d.createdAt.toISOString(),lastActivityAt:d.lastActivityAt.toISOString(),expiresAt:d.expiresAt.toISOString()}); return r;},async find(r){if(!r)return null;const h=hash(r);if(isDbConnected())return Mongo.findOne({tokenHash:h,revokedAt:null,expiresAt:{$gt:new Date()}});return jm.getAll().find(s=>s.tokenHash===h&&!s.revokedAt&&new Date(s.expiresAt).getTime()>Date.now())||null;},async revoke(r){if(!r)return;const h=hash(r);if(isDbConnected())return Mongo.updateOne({tokenHash:h},{revokedAt:new Date()});const s=jm.getAll().find(x=>x.tokenHash===h);if(s)jm.update(s.id,{revokedAt:new Date().toISOString()});}};
